//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictureWidget.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PictureWidget.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show pictures including GIFs.
        /// </summary>
        public static string PictureWidgetServer_Description_ShowPicturesIncludingGIFs {
            get {
                return ResourceManager.GetString("PictureWidgetServer_Description_ShowPicturesIncludingGIFs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string PictureWidgetServer_Name_Picture {
            get {
                return ResourceManager.GetString("PictureWidgetServer_Name_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Options.
        /// </summary>
        public static string SettingsUserControl_AdvancedOptions {
            get {
                return ResourceManager.GetString("SettingsUserControl_AdvancedOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Scale Font.
        /// </summary>
        public static string SettingsUserControl_AutoScaleFont {
            get {
                return ResourceManager.GetString("SettingsUserControl_AutoScaleFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string SettingsUserControl_Background {
            get {
                return ResourceManager.GetString("SettingsUserControl_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string SettingsUserControl_Bottom {
            get {
                return ResourceManager.GetString("SettingsUserControl_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string SettingsUserControl_Center {
            get {
                return ResourceManager.GetString("SettingsUserControl_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string SettingsUserControl_CenterVertical {
            get {
                return ResourceManager.GetString("SettingsUserControl_CenterVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string SettingsUserControl_DesignHeader {
            get {
                return ResourceManager.GetString("SettingsUserControl_DesignHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal:.
        /// </summary>
        public static string SettingsUserControl_Horizontal {
            get {
                return ResourceManager.GetString("SettingsUserControl_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string SettingsUserControl_Image {
            get {
                return ResourceManager.GetString("SettingsUserControl_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string SettingsUserControl_ImageHeader {
            get {
                return ResourceManager.GetString("SettingsUserControl_ImageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string SettingsUserControl_Left {
            get {
                return ResourceManager.GetString("SettingsUserControl_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Color.
        /// </summary>
        public static string SettingsUserControl_OverlayColor {
            get {
                return ResourceManager.GetString("SettingsUserControl_OverlayColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Font.
        /// </summary>
        public static string SettingsUserControl_OverlayFont {
            get {
                return ResourceManager.GetString("SettingsUserControl_OverlayFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Offset.
        /// </summary>
        public static string SettingsUserControl_OverlayOffset {
            get {
                return ResourceManager.GetString("SettingsUserControl_OverlayOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Position.
        /// </summary>
        public static string SettingsUserControl_OverlayPosition {
            get {
                return ResourceManager.GetString("SettingsUserControl_OverlayPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Text.
        /// </summary>
        public static string SettingsUserControl_OverlayText {
            get {
                return ResourceManager.GetString("SettingsUserControl_OverlayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string SettingsUserControl_Right {
            get {
                return ResourceManager.GetString("SettingsUserControl_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string SettingsUserControl_Select {
            get {
                return ResourceManager.GetString("SettingsUserControl_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Slideshow.
        /// </summary>
        public static string SettingsUserControl_SettingsUserControl_FolderSlideshow {
            get {
                return ResourceManager.GetString("SettingsUserControl_SettingsUserControl_FolderSlideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Image.
        /// </summary>
        public static string SettingsUserControl_SettingsUserControl_SingleImage {
            get {
                return ResourceManager.GetString("SettingsUserControl_SettingsUserControl_SingleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string SettingsUserControl_Top {
            get {
                return ResourceManager.GetString("SettingsUserControl_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string SettingsUserControl_Type {
            get {
                return ResourceManager.GetString("SettingsUserControl_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Global Theme.
        /// </summary>
        public static string SettingsUserControl_UseGlobalTheme {
            get {
                return ResourceManager.GetString("SettingsUserControl_UseGlobalTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vector Color.
        /// </summary>
        public static string SettingsUserControl_VectorColor {
            get {
                return ResourceManager.GetString("SettingsUserControl_VectorColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vector Scale.
        /// </summary>
        public static string SettingsUserControl_VectorScale {
            get {
                return ResourceManager.GetString("SettingsUserControl_VectorScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical:.
        /// </summary>
        public static string SettingsUserControl_Vertical {
            get {
                return ResourceManager.GetString("SettingsUserControl_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Wrap.
        /// </summary>
        public static string SettingsUserControl_WordWrap {
            get {
                return ResourceManager.GetString("SettingsUserControl_WordWrap", resourceCulture);
            }
        }
    }
}
